spring.application.name=reports
server.port=8083

# Enable debug logging for web requests
logging.level.org.springframework.web=DEBUG
logging.level.com.expense=DEBUG


# DB config (local)
#spring.datasource.url=jdbc:mysql://localhost:3306/report_service?serverTimezone=Asia/Kolkata
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#hibernate.show_sql=true;
#
#spring.jpa.hibernate.ddl-auto=update

#spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.hibernate.SQL=debug
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=trace


# JDBC Config
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Enable SQL logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# KAfka

spring.kafka.bootstrap-servers=kafka:9092
# Consumer config
spring.kafka.consumer.group-id=report-group

spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.value.default.type=com.reports.reports.dto.IncomeKafkaMessage

# Use ErrorHandlingDeserializer with JSON
#spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
# Topics
app.kafka.income-topic=income-topic
app.kafka.expense-topic=expense-topic
app.kafka.category-topic=category-topic
app.kafka.income-category-topic=income-category-topic

#spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
#spring.kafka.consumer.bootstrap-servers=localhost:9092
# Class to deserialize to
#spring.kafka.consumer.properties.spring.json.value.default.type=com.reports.reports.dto.IncomeKafkaMessage

# Trusted packages
#spring.kafka.consumer.properties.spring.json.trusted.packages=*
#logging.level.org.apache.kafka=DEBUG
#logging.level.org.springframework.kafka=DEBUG