spring.application.name=AI-FINANCIAL-ANALYSIS-SERVICE
server.port=8082

# Database config (shared with expense service)
spring.datasource.url=jdbc:mysql://localhost:3306/expense_db?serverTimezone=Asia/Kolkata
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA config (read-only)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=false


# Groq AI API
groq.api.key=${GROQ_API_KEY:}

# Logging
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%file:%line] - %msg%n
logging.level.com.aifinancial=INFO
